version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: disabled
