version: 2.1

executors:
  php81:
    docker:
      - image: cimg/php:8.1
  php82:
    docker:
      - image: cimg/php:8.2
  php83:
    docker:
      - image: cimg/php:8.3

jobs:
  test:
    parameters:
      laravel-version:
        type: string
      php-executor:
        type: string
    executor: << parameters.php-executor >>
    steps:
      - run: sudo -E pecl install pcov && sudo -E docker-php-ext-enable pcov
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
            - v2-dependencies-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-
      - run: composer require illuminate/log=^<< parameters.laravel-version >> illuminate/queue=^<< parameters.laravel-version >> illuminate/support=^<< parameters.laravel-version >>
      - save_cache:
          key: v2-dependencies-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer phpunit

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              laravel-version: ['10.0']
              php-executor: [php81, php82, php83]
