version: 2.1

executors:
  php80:
    docker:
      - image: cimg/php:8.0
  php81:
    docker:
      - image: cimg/php:8.1

jobs:
  test:
    parameters:
      laravel-version:
        type: string
      php-executor:
        type: string
    executor: << parameters.php-executor >>
    steps:
      - checkout
      - run: composer require illuminate/log=<< parameters.laravel-version >> illuminate/queue=<< parameters.laravel-version >> illuminate/support=<< parameters.laravel-version >>
      - run: composer update --prefer-lowest
      - run: composer phpunit
      - run: composer update
      - run: composer phpunit

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              laravel-version: ['^8.79', '^9.0', '^10.0']
              php-executor: [php80, php81]
            exclude:
              - laravel-version: '^10.0'
                php-executor: 'php80'
