version: 2.1

executors:
  php80:
    docker:
      - image: cimg/php:8.0
  php81:
    docker:
      - image: cimg/php:8.1

jobs:
  test:
    parameters:
      laravel-version:
        type: string
      php-executor:
        type: string
    executor: << parameters.php-executor >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-lowest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
            - v1-dependencies-lowest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-
      - run: composer require --prefer-lowest illuminate/log=^<< parameters.laravel-version >> illuminate/queue=^<< parameters.laravel-version >> illuminate/support=^<< parameters.laravel-version >>
      - save_cache:
          key: v1-dependencies-lowest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer phpunit
      - restore_cache:
          keys:
            - v1-dependencies-highest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
            - v1-dependencies-highest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-
      - run: composer update
      - save_cache:
          key: v1-dependencies-highest-<< parameters.php-executor >>-laravel-<< parameters.laravel-version >>-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer phpunit

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              laravel-version: ['8.79', '9.0']
              php-executor: [php80, php81]
